#!/bin/bash
# scripts/help-parametrik.sh
# Show usage information for all parametrik scripts

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Parametrik Script'ler - Kullanım Kılavuzu            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}1. check-task.sh${NC} - Checkbox İşaretleme"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Kullanım:${NC}"
echo "  ./scripts/check-task.sh <task-file> <task-text>"
echo ""
echo -e "${YELLOW}Parametreler:${NC}"
echo "  <task-file>    - Task dosyasının yolu"
echo "  <task-text>    - İşaretlenecek checkbox'ın text'i (partial match OK)"
echo ""
echo -e "${YELLOW}Örnekler:${NC}"
echo "  ./scripts/check-task.sh .claude/active/feature-add-dark-mode.md \"Create ThemeContext\""
echo "  ./scripts/check-task.sh .claude/active/feature-add-dark-mode.md \"Add toggle to Header\""
echo ""
echo -e "${YELLOW}Not:${NC} Task text checkbox içindeki text ile eşleşmeli (kısmi eşleşme yeterli)"
echo ""

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}2. update-progress.sh${NC} - Progress Log'a Kayıt Ekleme"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Kullanım:${NC}"
echo "  ./scripts/update-progress.sh <task-file> <message>"
echo ""
echo -e "${YELLOW}Parametreler:${NC}"
echo "  <task-file>    - Task dosyasının yolu"
echo "  <message>      - Progress Log'a eklenecek mesaj"
echo ""
echo -e "${YELLOW}Örnekler:${NC}"
echo "  ./scripts/update-progress.sh .claude/active/feature-add-dark-mode.md \"Plan 1 completed\""
echo "  ./scripts/update-progress.sh .claude/active/feature-add-dark-mode.md \"Fixed bug in theme toggle\""
echo "  ./scripts/update-progress.sh .claude/active/feature-add-dark-mode.md \"All components styled for dark mode\""
echo ""
echo -e "${YELLOW}Not:${NC} Tarih/saat otomatik olarak eklenir"
echo ""

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}3. set-priority.sh${NC} - Priority Değiştirme"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Kullanım:${NC}"
echo "  ./scripts/set-priority.sh <task-file> <priority>"
echo ""
echo -e "${YELLOW}Parametreler:${NC}"
echo "  <task-file>    - Task dosyasının yolu"
echo "  <priority>     - Priority değeri: ${GREEN}high${NC}, ${YELLOW}medium${NC}, ${RED}low${NC}"
echo ""
echo -e "${YELLOW}Örnekler:${NC}"
echo "  ./scripts/set-priority.sh .claude/active/feature-add-dark-mode.md high"
echo "  ./scripts/set-priority.sh .claude/active/feature-add-dark-mode.md medium"
echo "  ./scripts/set-priority.sh .claude/active/feature-add-dark-mode.md low"
echo ""

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}4. add-tags.sh${NC} - Tag Ekleme/Düzenleme"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Kullanım:${NC}"
echo "  ./scripts/add-tags.sh <task-file> <tag1> [tag2] [tag3] ..."
echo ""
echo -e "${YELLOW}Parametreler:${NC}"
echo "  <task-file>    - Task dosyasının yolu"
echo "  <tag1>         - Eklenecek tag (zorunlu)"
echo "  [tag2] ...     - Ek tag'ler (opsiyonel, birden fazla olabilir)"
echo ""
echo -e "${YELLOW}Örnekler:${NC}"
echo "  ./scripts/add-tags.sh .claude/active/feature-add-dark-mode.md ui theme"
echo "  ./scripts/add-tags.sh .claude/active/feature-add-dark-mode.md auth security frontend"
echo "  ./scripts/add-tags.sh .claude/active/bug-login-fails.md bug critical"
echo ""
echo -e "${YELLOW}Not:${NC} Duplicate tag'ler otomatik olarak filtrelenir, tag'ler alfabetik sıraya konur"
echo ""

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}5. start-task.sh${NC} - Task'a Başlama"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Kullanım:${NC}"
echo "  ./scripts/start-task.sh <task-file> [message]"
echo ""
echo -e "${YELLOW}Parametreler:${NC}"
echo "  <task-file>    - Task dosyasının yolu"
echo "  [message]      - Progress Log mesajı (opsiyonel, varsayılan: \"Started working on this task\")"
echo ""
echo -e "${YELLOW}Örnekler:${NC}"
echo "  ./scripts/start-task.sh .claude/active/feature-add-dark-mode.md"
echo "  ./scripts/start-task.sh .claude/active/feature-add-dark-mode.md \"Starting Plan 1\""
echo "  ./scripts/start-task.sh .claude/active/feature-add-dark-mode.md \"Starting Plan 2: UI Components\""
echo ""
echo -e "${YELLOW}Ne Yapar:${NC}"
echo "  - Status'u 'in-progress' yapar"
echo "  - Progress Log'a kayıt ekler"
echo "  - Tarih/saat otomatik eklenir"
echo ""

echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Hızlı Referans${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}Checkbox işaretle:${NC}"
echo "  ./scripts/check-task.sh <file> <task-text>"
echo ""
echo -e "${GREEN}Progress kaydet:${NC}"
echo "  ./scripts/update-progress.sh <file> <message>"
echo ""
echo -e "${GREEN}Priority ayarla:${NC}"
echo "  ./scripts/set-priority.sh <file> <high|medium|low>"
echo ""
echo -e "${GREEN}Tag ekle:${NC}"
echo "  ./scripts/add-tags.sh <file> <tag1> [tag2] ..."
echo ""
echo -e "${GREEN}Task'a başla:${NC}"
echo "  ./scripts/start-task.sh <file> [message]"
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Detaylı dokümantasyon:${NC}"
echo "  scripts/README-parametrik-scripts.md"
echo ""
